version: '2'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka-rest:
    image: nodefluent/kafka-rest
    ports:
      - 8082:8082
    links:
      - kafka
      - zookeeper
    depends_on:
      - kafka
      - zookeeper
    environment:
      DEBUG: "*"

  kafka-rest-ui:
      image: nodefluent/kafka-rest-ui
      ports:
        - 8000:8000
      links:
        - kafka-rest
      depends_on:
        - kafka-rest
      environment:
        DEBUG: "*"
        REACT_APP_KAFKA_REST_URL: "http://kafka-rest:8082/"
        REACT_APP_TIMEOUT: "3000"
        PROXY: "yes"
        BASIC_AUTH_USER: "admin"
        BASIC_AUTH_PASSWORD: "admin"
  kafka:
    image: wurstmeister/kafka
    hostname: kafka
    ports:
      - "9092:9092"
    links:
      - zookeeper:zk
    environment:
      KAFKA_ADVERTISED_HOST_NAME: "kafka"
      KAFKA_ADVERTISED_PORT: "9092"
      KAFKA_ZOOKEEPER_CONNECT: "zk:2181"
      KAFKA_BROKER_ID: 1
      KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://kafka:9092"
      KAFKA_LISTENERS: "PLAINTEXT://:9092"
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
